### ISSUE TITLE
[Request/Bug] Make player unequip higher tier Curios / Compatibility with Curios

### ISSUE THREAD

**Issue by Luningor** [PydingAbsorber/AscendTiers#1]
Although it certainly makes players unable to use items and armor, and even unequips it if it's put forcefully with creative, it can't yet prevent a player from equiping a curio on a curio slot.
My request is to make the mod compatible with Curios, if possible.

**Comment by PydingAbsorber** [comment]
I didn't understand the problem, so curios can be worn even if it's tier is higher? I tested that on many modpacks and it worked as it should be for me with curios

**Comment by Luningor** [comment]
Must've been a weird bug on my end then, because I now have booted my modpack and it worked as intended. I blame an outdated mod for it, thanks for replying ^^"
