### ISSUE TITLE
[Bug] Big packets impede the player logging into a world when there's too much tiered items

### ISSUE THREAD

**Issue by Luningor** [PydingAbsorber/AscendTiers#2]
**[Disclaimer]**
I'll make a few assumptions based on my limited knowledge and some observations I've made while testing this.
Feel free to ignore them if that is not the case. Thank you for your time, regardless.

**[Description]**
When adding lots of items/mobs to the tiered system, the world will forcefully close upon reentry because  the packets the player sends are way too big. [ I believe this is because the tier system is a live write/read system. A potential solution would be to only sync in batches upon entry and upon server reload ].

**[Steps to reproduce]**
- Fill around 20/25 double chests worth of different items.
- Tier them up.
- Exit world.
- Enter world again.

**[Adjunt related files]**
- Log file: 
[2024-09-12-6.log](https://github.com/user-attachments/files/16995997/2024-09-12-6.log)
- Current config file: 
[at-common.txt](https://github.com/user-attachments/files/16995977/at-common.txt)

**Comment by PydingAbsorber** [comment]
Yes I encountered this problem on my server and just removed sync with packets. Now config is on server side in world package ,,serverconfig,, it's syncing automatically
